import type { Obligation, AgentMessage, PolicyTension } from "./store";

// ─── Mock Obligations ─────────────────────────────────────────────────────────

export const mockObligations: Obligation[] = [
  {
    id: "OBL-001",
    regulation: "RBI Master Direction 2023",
    jurisdiction: "India",
    department: "Treasury & Finance",
    description: "Maintain minimum capital adequacy ratio of 11.5% under Pillar 1 requirements including credit, market, and operational risk.",
    riskLevel: "CRITICAL",
    riskScore: 94,
    status: "PENDING",
    confidence: 0.97,
    dueDate: "2025-06-30",
    assignedBy: "AI Router v2.1",
  },
  {
    id: "OBL-002",
    regulation: "DPDP Act 2023",
    jurisdiction: "India",
    department: "Data Privacy & IT",
    description: "Appoint a Data Protection Officer and register with the Data Protection Board within 90 days of commencement.",
    riskLevel: "HIGH",
    riskScore: 81,
    status: "PENDING",
    confidence: 0.92,
    dueDate: "2025-07-15",
    assignedBy: "AI Router v2.1",
  },
  {
    id: "OBL-003",
    regulation: "SEBI Circular SEBI/HO/MIRSD",
    jurisdiction: "India",
    department: "Legal & Compliance",
    description: "Implement automated KYC re-verification for dormant accounts exceeding 24 months of inactivity.",
    riskLevel: "HIGH",
    riskScore: 76,
    status: "APPROVED",
    confidence: 0.88,
    dueDate: "2025-08-01",
    assignedBy: "AI Router v2.1",
  },
  {
    id: "OBL-004",
    regulation: "ISO 27001:2022",
    jurisdiction: "Global",
    department: "Information Security",
    description: "Conduct annual penetration testing and vulnerability assessments on all Tier-1 financial systems.",
    riskLevel: "MEDIUM",
    riskScore: 58,
    status: "PENDING",
    confidence: 0.85,
    dueDate: "2025-09-30",
    assignedBy: "AI Router v2.1",
  },
  {
    id: "OBL-005",
    regulation: "FEMA 2000 (Amendment 2024)",
    jurisdiction: "India",
    department: "Treasury & Finance",
    description: "File quarterly ECB reports (Form ECB-2) within 7 working days of month-end for all outstanding external commercial borrowings.",
    riskLevel: "HIGH",
    riskScore: 79,
    status: "PENDING",
    confidence: 0.91,
    dueDate: "2025-07-07",
    assignedBy: "AI Router v2.1",
  },
  {
    id: "OBL-006",
    regulation: "Basel III Pillar 3",
    jurisdiction: "Global",
    department: "Risk Management",
    description: "Publish quarterly Pillar 3 disclosures on the company website within 45 days of quarter-end.",
    riskLevel: "MEDIUM",
    riskScore: 62,
    status: "APPROVED",
    confidence: 0.89,
    dueDate: "2025-08-15",
    assignedBy: "AI Router v2.1",
  },
  {
    id: "OBL-007",
    regulation: "PMLA 2002 (Amendment 2023)",
    jurisdiction: "India",
    department: "AML & Sanctions",
    description: "Submit Suspicious Transaction Reports (STRs) to FIU-IND within 7 working days of suspicion arising.",
    riskLevel: "CRITICAL",
    riskScore: 96,
    status: "PENDING",
    confidence: 0.98,
    dueDate: "2025-06-20",
    assignedBy: "AI Router v2.1",
  },
  {
    id: "OBL-008",
    regulation: "IRDAI Corporate Governance",
    jurisdiction: "India",
    department: "Board Secretariat",
    description: "Ensure Board Risk Management Committee meets at least quarterly with documented minutes submitted to IRDAI.",
    riskLevel: "LOW",
    riskScore: 38,
    status: "APPROVED",
    confidence: 0.79,
    dueDate: "2025-10-01",
    assignedBy: "AI Router v2.1",
  },
];

// ─── Mock Agent Messages ───────────────────────────────────────────────────────

export const mockAgentMessages: AgentMessage[] = [
  {
    id: "msg-001",
    agent: "VERIFIER",
    content: "Initiating document ingestion pipeline. Document: RBI_Master_Direction_Q3_2025.pdf. SHA-256: a3f2d1e9c8b7... Extracting structured obligations from 47 pages.",
    timestamp: "09:41:02",
    type: "action",
  },
  {
    id: "msg-002",
    agent: "VERIFIER",
    content: "TEMPORAL ANOMALY DETECTED: Document metadata creation_date=2024-11-15 but embedded XREF table references standard published 2025-02-01. Flagging for forensic review. Confidence of forgery: 87%.",
    timestamp: "09:41:09",
    type: "thought",
  },
  {
    id: "msg-003",
    agent: "CRITIC",
    content: "OBJECTION [SEVERITY: MEDIUM] — VERIFIER's forgery confidence may be inflated. The XREF discrepancy is consistent with amended re-publication patterns used by RBI. Cross-referencing gazette notification GN-2025-114...",
    timestamp: "09:41:14",
    type: "disagreement",
    resolved: false,
  },
  {
    id: "msg-004",
    agent: "VERIFIER",
    content: "Acknowledged CRITIC's challenge. Querying RBI official gazette database... RESULT: Gazette GN-2025-114 confirms amendment issued 2025-02-01 superseding original. Revising forgery confidence to 12%. Document is AUTHENTIC.",
    timestamp: "09:41:22",
    type: "thought",
  },
  {
    id: "msg-005",
    agent: "CRITIC",
    content: "RESOLUTION ACCEPTED. Disagreement resolved. Document authenticity confirmed. Proceeding with obligation extraction.",
    timestamp: "09:41:25",
    type: "resolution",
    resolved: true,
  },
  {
    id: "msg-006",
    agent: "PLANNER",
    content: "Obligation extraction complete. Identified 8 primary obligations across 4 regulatory frameworks: RBI (3), DPDP (1), SEBI (2), FEMA (2). Initiating causal dependency mapping...",
    timestamp: "09:41:30",
    type: "action",
  },
  {
    id: "msg-007",
    agent: "PLANNER",
    content: "Building causal DAG. OBL-001 (Capital Adequacy) is a blocker for OBL-005 (FEMA ECB). OBL-002 (DPO Appointment) must precede OBL-004 (Pen Testing). Critical path identified: 14-node execution tree.",
    timestamp: "09:41:38",
    type: "thought",
  },
  {
    id: "msg-008",
    agent: "CRITIC",
    content: "OBJECTION [SEVERITY: HIGH] — PLANNER's routing of OBL-003 (KYC) to 'Legal & Compliance' is suboptimal. Historical precedent (ServiceNow ticket SN-44892) shows 'Operations & KYC' team has 40% faster resolution time.",
    timestamp: "09:41:44",
    type: "disagreement",
    resolved: false,
  },
  {
    id: "msg-009",
    agent: "PLANNER",
    content: "CRITIC's suggestion acknowledged. Querying historical resolution metrics... Confirmed: Operations & KYC team: avg 4.2 days vs Legal: avg 7.1 days for equivalent obligations. Updating routing decision.",
    timestamp: "09:41:51",
    type: "thought",
  },
  {
    id: "msg-010",
    agent: "CRITIC",
    content: "RESOLUTION ACCEPTED. Routing override applied. WORM ledger entry created: ROUTE_OVERRIDE_SN-44892. All obligations queued for Chief Compliance Officer review.",
    timestamp: "09:41:55",
    type: "resolution",
    resolved: true,
  },
  {
    id: "msg-011",
    agent: "PLANNER",
    content: "POLICY TENSION DETECTED: RBI Section 7(c) mandates data residency within Indian jurisdiction. DPDP Section 16(2) permits cross-border transfer with Board approval. Flagging for compensating control generation...",
    timestamp: "09:42:03",
    type: "thought",
  },
  {
    id: "msg-012",
    agent: "VERIFIER",
    content: "Pipeline execution complete. 8 obligations extracted. 2 routing disagreements resolved. 1 policy tension flagged. DAG constructed with 14 nodes. Syncing to MAP Review Dashboard for CCO approval.",
    timestamp: "09:42:10",
    type: "action",
  },
];

// ─── Mock Policy Tensions ──────────────────────────────────────────────────────

export const mockTensions: PolicyTension[] = [
  {
    id: "TEN-001",
    title: "RBI Data Residency vs. DPDP Cross-Border Transfer",
    severity: "CRITICAL",
    regulationA: {
      name: "RBI Master Direction on IT Framework §7(c)",
      excerpt: "All data pertaining to domestic financial transactions and customer PII must be stored exclusively within the geographic boundaries of India. No mirroring or replication to foreign jurisdictions is permitted without prior RBI approval.",
    },
    regulationB: {
      name: "DPDP Act 2023 §16(2)",
      excerpt: "A Data Fiduciary may transfer personal data outside India to countries notified by the Central Government, provided the Board of Directors approves the transfer and an equivalent data protection standard is maintained.",
    },
    contradiction: "RBI categorically prohibits foreign data replication for financial PII without RBI approval, while DPDP permits cross-border transfer with only Board-level approval. These approvals are separate, non-interchangeable authorities, creating a regulatory deadlock for cloud-hosted global platforms.",
    compensatingControl: "Implement a data locality tier: Segregate financial PII (RBI scope) on India-only infrastructure nodes, while non-financial personal data (DPDP scope) may utilize global CDN with Board approval. Dual-approval matrix must be maintained in the WORM ledger.",
    status: "UNRESOLVED",
  },
  {
    id: "TEN-002",
    title: "SEBI CSCRF vs. ISO 27001 Incident Response Timelines",
    severity: "HIGH",
    regulationA: {
      name: "SEBI CSCRF Framework 2024 §4.3",
      excerpt: "All Market Infrastructure Institutions must report cybersecurity incidents to SEBI within 6 hours of detection. Preliminary incident reports must include attack vector, affected systems, and estimated impact.",
    },
    regulationB: {
      name: "ISO 27001:2022 Annex A §5.26",
      excerpt: "The organization shall define, implement and communicate a process for responding to information security incidents. Incident response timelines shall be determined by the organization based on the criticality classification.",
    },
    contradiction: "ISO 27001 grants organizational discretion in setting response timelines, which may be calibrated to 24-48 hours for lower-severity incidents. SEBI's mandatory 6-hour window overrides this discretion for all incidents, creating a conflict when the ISO risk classification deems an incident low-severity but SEBI scope still applies.",
    compensatingControl: "Override ISO's internal classification for any incident involving market systems. Deploy automated SEBI incident notification workflow that triggers at T+1 hour with an auto-generated preliminary report, providing 5-hour buffer for human verification. Log override rationale in audit trail.",
    status: "ACKNOWLEDGED",
  },
  {
    id: "TEN-003",
    title: "PMLA Transaction Monitoring vs. DPDP Purpose Limitation",
    severity: "HIGH",
    regulationA: {
      name: "PMLA 2002 §12A (2023 Amendment)",
      excerpt: "Reporting entities must maintain records of all transactions above ₹10 lakhs for 10 years and make them available to FIU-IND on demand. Continuous transaction monitoring using AI/ML is mandated for entities in the high-risk category.",
    },
    regulationB: {
      name: "DPDP Act 2023 §6(1) — Purpose Limitation",
      excerpt: "Personal data shall only be processed for the specified purpose for which consent was obtained. Processing for purposes beyond those specified requires fresh consent or falls within the enumerated legitimate uses.",
    },
    contradiction: "PMLA's continuous AI-driven transaction monitoring processes customer behavioral patterns well beyond the 'payment processing' purpose for which financial data is typically collected. DPDP's purpose limitation principle may classify this as unauthorized secondary processing unless explicitly exempted.",
    compensatingControl: "Invoke DPDP §17(1)(b) exemption for legal obligations. Document a 'Regulatory Processing Notice' in the customer onboarding flow explicitly stating PMLA-mandated monitoring. This notice creates a valid consent framework aligned with both statutes.",
    status: "CONTROL_APPLIED",
  },
  {
    id: "TEN-004",
    title: "Basel III LCR vs. IRDAI Investment Guidelines",
    severity: "MEDIUM",
    regulationA: {
      name: "RBI Basel III LCR Guidelines §8",
      excerpt: "Banks must maintain a Liquidity Coverage Ratio of 100%, holding sufficient High-Quality Liquid Assets (HQLA) to survive a 30-day stress scenario. Government securities must comprise at least 60% of HQLA.",
    },
    regulationB: {
      name: "IRDAI Investment Regulations 2016 §27",
      excerpt: "Insurance companies shall invest not less than 25% of funds in infrastructure and social sector bonds. Concentration in government securities shall not exceed 40% of the total investment portfolio.",
    },
    contradiction: "For financial conglomerates with both banking and insurance subsidiaries, Basel III requires ≥60% in G-secs at the bank level while IRDAI caps G-sec holdings at 40% at the insurance subsidiary level. Consolidated group reporting creates an irreconcilable conflict.",
    compensatingControl: "Implement strict entity-level ring-fencing with separate investment pools for banking and insurance subsidiaries. Consolidated reporting must use segmented balance sheets. Obtain a no-objection from RBI for the consolidated view under conglomerate supervision guidelines.",
    status: "UNRESOLVED",
  },
];

// ─── Mock DAG Nodes & Edges ───────────────────────────────────────────────────

export const mockDagNodes = [
  { id: "n1", type: "dagNode", position: { x: 400, y: 50 }, data: { label: "Document Ingestion", dept: "IT Operations", sla: "T+0", status: "complete", riskLevel: "LOW" } },
  { id: "n2", type: "dagNode", position: { x: 150, y: 180 }, data: { label: "Capital Adequacy (OBL-001)", dept: "Treasury", sla: "T+30", status: "in-progress", riskLevel: "CRITICAL" } },
  { id: "n3", type: "dagNode", position: { x: 400, y: 180 }, data: { label: "DPO Appointment (OBL-002)", dept: "Data Privacy", sla: "T+90", status: "pending", riskLevel: "HIGH" } },
  { id: "n4", type: "dagNode", position: { x: 650, y: 180 }, data: { label: "STR Submission (OBL-007)", dept: "AML & Sanctions", sla: "T+7", status: "pending", riskLevel: "CRITICAL" } },
  { id: "n5", type: "dagNode", position: { x: 50, y: 330 }, data: { label: "FEMA ECB Reports (OBL-005)", dept: "Treasury", sla: "T+37", status: "blocked", riskLevel: "HIGH" } },
  { id: "n6", type: "dagNode", position: { x: 250, y: 330 }, data: { label: "Pillar 3 Disclosure (OBL-006)", dept: "Risk Mgmt", sla: "T+45", status: "pending", riskLevel: "MEDIUM" } },
  { id: "n7", type: "dagNode", position: { x: 450, y: 330 }, data: { label: "Pen Testing (OBL-004)", dept: "InfoSec", sla: "T+120", status: "pending", riskLevel: "MEDIUM" } },
  { id: "n8", type: "dagNode", position: { x: 650, y: 330 }, data: { label: "KYC Re-verification (OBL-003)", dept: "Operations", sla: "T+60", status: "pending", riskLevel: "HIGH" } },
  { id: "n9", type: "dagNode", position: { x: 750, y: 330 }, data: { label: "Board Risk Committee (OBL-008)", dept: "Board Sec.", sla: "T+90", status: "pending", riskLevel: "LOW" } },
  { id: "n10", type: "dagNode", position: { x: 150, y: 480 }, data: { label: "ServiceNow Ticket Creation", dept: "IT Ops", sla: "T+38", status: "pending", riskLevel: "LOW" } },
  { id: "n11", type: "dagNode", position: { x: 350, y: 480 }, data: { label: "CCO Final Sign-off", dept: "Compliance", sla: "T+50", status: "pending", riskLevel: "HIGH" } },
  { id: "n12", type: "dagNode", position: { x: 550, y: 480 }, data: { label: "Regulatory Submission Portal", dept: "Compliance", sla: "T+65", status: "pending", riskLevel: "MEDIUM" } },
  { id: "n13", type: "dagNode", position: { x: 350, y: 600 }, data: { label: "WORM Audit Log Sync", dept: "IT Ops", sla: "T+51", status: "pending", riskLevel: "LOW" } },
  { id: "n14", type: "dagNode", position: { x: 550, y: 600 }, data: { label: "External Auditor Review", dept: "Finance", sla: "T+90", status: "pending", riskLevel: "MEDIUM" } },
];

export const mockDagEdges = [
  { id: "e1-2", source: "n1", target: "n2", animated: true },
  { id: "e1-3", source: "n1", target: "n3", animated: true },
  { id: "e1-4", source: "n1", target: "n4", animated: true },
  { id: "e2-5", source: "n2", target: "n5" },
  { id: "e2-6", source: "n2", target: "n6" },
  { id: "e3-7", source: "n3", target: "n7" },
  { id: "e3-8", source: "n3", target: "n8" },
  { id: "e4-9", source: "n4", target: "n9" },
  { id: "e5-10", source: "n5", target: "n10" },
  { id: "e6-11", source: "n6", target: "n11" },
  { id: "e7-11", source: "n7", target: "n11" },
  { id: "e8-12", source: "n8", target: "n12" },
  { id: "e11-13", source: "n11", target: "n13" },
  { id: "e12-14", source: "n12", target: "n14" },
];
